TI2023-134: Metric accuracy vector
jaak-ai/drManhattan pull request #2
Opened 2023-01-28 00:17 UTC by Gbcards

2023-01-28 00:27 UTC, rcristian3 requested changes

2023-01-28 00:27 UTC, rcristian3 commented on src/packages/actions/vector.action.go
> +func worker(id int) bool {
usas esta funcionn ?

2023-01-28 00:50 UTC, Gbcards commented on src/packages/actions/vector.action.go
> +func worker(id int) bool {
Era una función de prueba, ya lo eliminé

2023-01-28 01:39 UTC, rcristian3 approved these changes

2023-01-30 14:41 UTC, merged

2023-02-09 23:59 UTC, rcristian3 commented
:tada: This PR is included in version 1.0.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/jaak-ai/drManhattan/releases/tag/v1.0.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-10 19:21 UTC, rcristian3 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/jaak-ai/drManhattan/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: